<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title>Knacksource Consulting & Training Services</title>\n"; 
echo "<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\n"; 
echo "<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\n"; 
echo "<script src=\"js/jquery.min.js\"></script>\n"; 
echo "<!-- Custom Theme files -->\n"; 
echo "<link href=\"css/style.css\" rel='stylesheet' type='text/css' />\n"; 
echo "<!-- Custom Theme files -->\n"; 
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"; 
echo "<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\n"; 
echo "</script>\n"; 
echo "<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n"; 
echo "<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n"; 
echo "<link href='http://fonts.googleapis.com/css?family=Open+Sans:100,300,400,600,700,800' rel='stylesheet' type='text/css'>\n"; 
echo "\n"; 
echo "<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\n"; 
echo "<script type=\"text/javascript\" src=\"js/easing.js\"></script>\n"; 
echo " <style>\n"; 
echo "  body {\n"; 
echo "      position: relative; \n"; 
echo "  }\n"; 
echo "  #home1 {color: #fff; background-color: #1E88E5;}\n"; 
echo "  #abc {color: #fff; background-color: #673ab7;}\n"; 
echo "  #service {color: #fff; background-color: #ff9800;}\n"; 
echo "  #whyus {color: #fff; background-color: #00bcd4;}\n"; 
echo "  #capability {color: #fff; background-color: #009688;}\n"; 
echo "  </style>\n"; 
echo "\n"; 
echo "  <!-- Start WOWSlider.com HEAD section -->\n"; 
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"engine1/style.css\" />\n"; 
echo "<script type=\"text/javascript\" src=\"engine1/jquery.js\"></script><script>function myFunction() {alert(\"Got your message. We will get in touch with you shortly!\");}</script>\n"; 
echo "<!-- End WOWSlider.com HEAD section -->\n"; 
echo "\n"; 
echo "</head>\n"; 
echo "<body data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"0\">\n"; 
echo "	<div class=\"header\" style=\"background-color:#ffffff\"> <!--  style=\"background-image:url('images/nav.png');\" -->\n"; 
echo "	  <div class=\"container\">\n"; 
echo "	  	<div class=\"header_top\">\n"; 
echo "			<ul class=\"header_box\">\n"; 
echo "				<!-- <li class=\"mobile_left\"><i class=\"mobile\"> </i><span>+91 9999999999</span></li> -->\n"; 
echo "				<li class=\"message\"><a href=\"#\"><i class=\"msg\"> </i><span>info@knacksource.com</span></a></li>\n"; 
echo "				<div class=\"clearfix\"> </div>\n"; 
echo "			</ul>\n"; 
echo "			<!--<ul class=\"facebook\">\n"; 
echo "		   	<li class=\"fb\"><a href=\"#\"><span> </span></a></li>\n"; 
echo "			</ul>-->\n"; 
echo "			<div class=\"clearfix\"> </div>\n"; 
echo "	    </div>\n"; 
echo "	  </div>\n"; 
echo "	</div>\n"; 
echo "	\n"; 
echo "	<div class=\"header_bottom\">\n"; 
echo "	  <div class=\"container\">\n"; 
echo "	  	<div class=\"logo\">\n"; 
echo "	  	   <a href=\"index.html\"><img src=\"images/logo1.png\" alt=\"\"/></a>\n"; 
echo "	  	</div>	  	\n"; 
echo "	  	  <div class=\"menu\">\n"; 
echo "	  	    <div class=\"h_menu4\"><!-- start h_menu4 -->\n"; 
echo "				<a class=\"toggleMenu\" href=\"#\">Menu</a><div class=\"nav_icon\"><img src=\"images/nav_icon.png\" alt=\"\"/></div>\n"; 
echo "				<ul class=\"nav\">\n"; 
echo "					<li class=\"active\"><a href=\"#home\" class=\"scroll\">Home</a></li>\n"; 
echo "					<li><a href=\"#abc\" class=\"scroll\">Your HR</a></li>\n"; 
echo "					<li><a href=\"#service\" class=\"scroll\">Services</a></li>\n"; 
echo "					<li><a href=\"#whyus\" class=\"scroll\">Why Us</a></li>\n"; 
echo "					<li><a href=\"#capability\" class=\"scroll\">Capacity</a></li>\n"; 
echo "					<li><a href=\"#train\" class=\"scroll\">Training</a></li>					\n"; 
echo "					<li><a href=\"#about\" class=\"scroll\">About Us</a></li>\n"; 
echo "                    <li><a href=\"#contactus\" class=\"scroll\">Contact Us</a></li>\n"; 
echo "				</ul>\n"; 
echo "				<script type=\"text/javascript\" src=\"js/nav.js\"></script>\n"; 
echo "			</div><!-- end h_menu4 -->\n"; 
echo "			<script type=\"text/javascript\">\n"; 
echo "			jQuery(document).ready(function($) {\n"; 
echo "				$(\".scroll\").click(function(event){		\n"; 
echo "					event.preventDefault();\n"; 
echo "					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\n"; 
echo "				});\n"; 
echo "			});\n"; 
echo "		    </script>			\n"; 
echo "	  </div>\n"; 
echo "	  </div>\n"; 
echo "	</div>\n"; 
echo "	\n"; 
echo "\n"; 
echo "<!--<div id=\"home1\">\n"; 
echo "<div class=\"container-fluid\" >\n"; 
echo "<div id=\"home\"class=\"carousel slide\" data-ride=\"carousel\">\n"; 
echo "	    \n"; 
echo " <div class=\"carousel-inner\" role=\"listbox\">\n"; 
echo "<div class=\"item active\">\n"; 
echo "<img src=\"images/slider11.jpg\" alt=\"2\"  class=\"img-responsive animated bounceIn\" />\n"; 
echo "<br/>\n"; 
echo " </div>\n"; 
echo "\n"; 
echo "<div class=\"item\">\n"; 
echo "<img src=\"images/1.jpg\" alt=\"2\"  class=\"img-responsive animated bounceIn\" />\n"; 
echo "<br/>\n"; 
echo "\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "<div class=\"item\">\n"; 
echo " <img src=\"images/banner.jpg\" alt=\"1\" class=\"img-responsive animated rotateInDownLeft\" />\n"; 
echo "<br/>\n"; 
echo "</div>\n"; 
echo "<ol class=\"carousel-indicators\">\n"; 
echo "    <li data-target=\"#home\" data-slide-to=\"0\" class=\"active\"></li>\n"; 
echo "    <li data-target=\"#home\" data-slide-to=\"1\"></li> \n"; 
echo "	<li data-target=\"#home\" data-slide-to=\"2\"></li>\n"; 
echo "  </ol>\n"; 
echo "</div>\n"; 
echo " </div>\n"; 
echo " </div>\n"; 
echo "</div>-->\n"; 
echo "\n"; 
echo "<!-- Start WOWSlider.com BODY section -->\n"; 
echo "\n"; 
echo "<div id=\"wowslider-container1\">\n"; 
echo "<div class=\"ws_images\" id=\"home\"><ul>\n"; 
echo "		<li><img src=\"data1/images/slide1.jpg\" alt=\"\" title=\"\" id=\"wows1_0\"/></li>\n"; 
echo "		<li><img src=\"data1/images/slide2.jpg\" alt=\"\" title=\"\" id=\"wows1_1\"/></a></li>\n"; 
echo "		<li><img src=\"data1/images/slide3.jpg\" alt=\"\" title=\"\" id=\"wows1_2\"/></li>\n"; 
echo "	</ul></div>	\n"; 
echo "<div class=\"ws_shadow\"></div>\n"; 
echo "</div>	\n"; 
echo "<script type=\"text/javascript\" src=\"engine1/wowslider.js\"></script>\n"; 
echo "<script type=\"text/javascript\" src=\"engine1/script.js\"></script>\n"; 
echo "<!-- End WOWSlider.com BODY section -->\n"; 
echo "	   \n"; 
echo "<div class=\"main\">\n"; 
echo "    <div id=\"abc\">		\n"; 
echo "		<div class=\"third\">\n"; 
echo "			<div class=\"container\" style=\"color:#000\">\n"; 
echo "       			 <div class=\"gallery-head text-center\">\n"; 
echo "				  <h3 style=\"color:#FFF\">Your HR partner for success</h3>\n"; 
echo "				  <p> </p>\n"; 
echo "				  <span> </span>\n"; 
echo "			    </div>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic1.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Delivering bespoke HR solutions and professional HR services is our\n"; 
echo "						passion. We help you transform your business through the effective\n"; 
echo "						use of your Human Resources.</h4>\n"; 
echo "			    	</li>			    	\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>We work in partnership with you to implement appropriate HR\n"; 
echo "						interventions and solutions that ultimately deliver your business\n"; 
echo "						desired outcomes.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic2.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic3.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>We are partners to your company's success.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			     <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>We offer a tailored approach to meeting our clients' individual needs.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic4.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "       		</div>\n"; 
echo "       		<div class=\"container\" style=\"color:#000\">\n"; 
echo "       			 <div class=\"gallery-head text-center\">\n"; 
echo "				  <h3 style=\"color:#FFF\">Your HR, our Passion</h3>\n"; 
echo "				  <p> </p>\n"; 
echo "				  <span> </span>\n"; 
echo "			    </div>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic5.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Our focus is on delivering HR solutions that will help you achieve your\n"; 
echo "						performance and profitability goals. We have the right tools,\n"; 
echo "						processes, methodologies and systems to deliver our HR services to\n"; 
echo "						very high and measurable service level standards.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Our capacity building interventions will, among others, enable you\n"; 
echo "						bring talent to your company, harness the talent within your company\n"; 
echo "						and manage it effectively to grow and add value to your business.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic6.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic7.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Mindful of the fact that 'one solution does not fit all' our solutions and\n"; 
echo "						services are shaped around your exact requirement, fitting your\n"; 
echo "						overall business strategy, culture and values.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			     <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>We offer a tailored approach to meeting our clients' individual needs.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic8.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "       		</div>\n"; 
echo "       	</div>\n"; 
echo "		</div>\n"; 
echo "        <!-- <div class=\"work\" id=\"work\">\n"; 
echo "       		<div class=\"container\">\n"; 
echo "       			<div class=\"work_top text-center\">\n"; 
echo "				  <h3>Our Work</h3>\n"; 
echo "				  <p>We are added our featured works below</p>\n"; 
echo "				  <span> </span>\n"; 
echo "			    </div>\n"; 
echo "			    <div class=\"col_1_of_4 span_1_of_4\">\n"; 
echo "			     <div class=\"port-grid\">\n"; 
echo "					<div class=\"port-grid-text\">\n"; 
echo "					  <img src=\"images/arrow_icon.png\" alt=\"\"/>\n"; 
echo "					  <h3>Project Name</h3>\n"; 
echo "					  <p>Facebook Marketing</p>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"port-grid-pic block last\">\n"; 
echo "					  <a href=\"#\" class=\"b-link-stripe b-animate-go  thickbox\">\n"; 
echo "					  <img src=\"images/w1.jpg\" class=\"img-responsive\" style=\"top: 0px;\"><div class=\"b-wrapper\"><h2 class=\"b-animate b-from-left    b-delay03 \"><img src=\"images/plus.png\" alt=\"\" style=\"top: 0px;\"></h2>\n"; 
echo "					   </div></a>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"clearfix\"> </div>\n"; 
echo "				 </div>\n"; 
echo "			   </div>\n"; 
echo "			   <div class=\"col_1_of_4 span_1_of_4\">\n"; 
echo "			     <div class=\"port-grid\">\n"; 
echo "					<div class=\"port-grid-text\">\n"; 
echo "					  <img src=\"images/arrow_icon.png\" alt=\"\"/>\n"; 
echo "					  <h3>Project Name</h3>\n"; 
echo "					  <p>Landing Page</p>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"port-grid-pic block last\">\n"; 
echo "					  <a href=\"#\" class=\"b-link-stripe b-animate-go  thickbox\">\n"; 
echo "					  <img src=\"images/w2.jpg\" class=\"img-responsive\" style=\"top: 0px;\"><div class=\"b-wrapper\"><h2 class=\"b-animate b-from-left    b-delay03 \"><img src=\"images/plus.png\" alt=\"\" style=\"top: 0px;\"></h2>\n"; 
echo "					   </div></a>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"clearfix\"> </div>\n"; 
echo "				 </div>\n"; 
echo "			    </div>\n"; 
echo "			    <div class=\"col_1_of_4 span_1_of_4\">\n"; 
echo "			     <div class=\"port-grid\">\n"; 
echo "					<div class=\"port-grid-pic block last\">\n"; 
echo "					  <a href=\"#\" class=\"b-link-stripe b-animate-go  thickbox\">\n"; 
echo "					  <img src=\"images/w3.jpg\" class=\"img-responsive\" style=\"top: 0px;\"><div class=\"b-wrapper\"><h2 class=\"b-animate b-from-left    b-delay03 \"><img src=\"images/plus.png\" alt=\"\" style=\"top: 0px;\"></h2>\n"; 
echo "					   </div></a>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"port-grid-text\">\n"; 
echo "					  <img src=\"images/arrow_icon.png\" alt=\"\"/>\n"; 
echo "					  <h3>Project Name</h3>\n"; 
echo "					  <p>Facebook Marketing</p>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"clearfix\"> </div>\n"; 
echo "				 </div>\n"; 
echo "			    </div>\n"; 
echo "			    <div class=\"col_1_of_4 span_1_of_4\">\n"; 
echo "			     <div class=\"port-grid\">\n"; 
echo "					<div class=\"port-grid-pic block last\">\n"; 
echo "					  <a href=\"#\" class=\"b-link-stripe b-animate-go  thickbox\">\n"; 
echo "					  <img src=\"images/w4.jpg\" class=\"img-responsive\" style=\"top: 0px;\"><div class=\"b-wrapper\"><h2 class=\"b-animate b-from-left    b-delay03 \"><img src=\"images/plus.png\" alt=\"\" style=\"top: 0px;\"></h2>\n"; 
echo "					   </div></a>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"port-grid-text\">\n"; 
echo "					  <img src=\"images/arrow_icon.png\" alt=\"\"/>\n"; 
echo "					  <h3>Project Name</h3>\n"; 
echo "					  <p>Landing Page</p>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"clearfix\"> </div>\n"; 
echo "				 </div>\n"; 
echo "			   </div>\n"; 
echo "		   </div>\n"; 
echo "       	</div>-->\n"; 
echo "       	<div class=\"fourth\" id=\"service\">\n"; 
echo "			<div class=\"container\" style=\"color:#000\">\n"; 
echo "       			 <div class=\"gallery-head text-center\">\n"; 
echo "				  <h3 style=\"color:#FFF\">Our services</h3><br/>\n"; 
echo "				  <h4 style=\"color:#FFF\">We provide workable and effective solutions fitting your overall business strategy, culture and values. Our consulting services include:</h4>\n"; 
echo "				  <span> </span>\n"; 
echo "			    </div>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic9.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Developing an HR Strategy which is perfectly in line with your\n"; 
echo "						business strategy.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Organizational design for start-ups as well as restructuring for\n"; 
echo "						existing businesses.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic10.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic11.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Job Analysis and role profiling (as a baseline for other HR functions).</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			     <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Design of a robust Performance Management system, outlining\n"; 
echo "						critical KPIs together with all supporting templates, systems and\n"; 
echo "						processes for its effective implementation.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic12.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic13.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Design of effective Employee Communication and Feedback mechanisms.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			     <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Design of a Rewards and Recognition program that reinforces success.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic14.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "       		</div>\n"; 
echo "       	</div>\n"; 
echo "       	<div class=\"second\" id=\"whyus\">\n"; 
echo "			<div class=\"container\" style=\"color:#000\">\n"; 
echo "       			 <div class=\"gallery-head text-center\">\n"; 
echo "				  <h3 style=\"color:#FFF\">Our approach</h3>\n"; 
echo "				  <p> </p>\n"; 
echo "				  <span> </span>\n"; 
echo "			    </div>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic15.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>We adopt a highly personalizes style in our delivery, working with you\n"; 
echo "						to identify your specific needs and delivering tailored HR Solutions\n"; 
echo "						based on your unique needs. Our services are uniquely branded for\n"; 
echo "						each client. We work as partners to your business success. We focus\n"; 
echo "						on the outcomes of our interventions on your business, and that is\n"; 
echo "						our value proposition.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>We maintain very high client service standards and se aim to achieve\n"; 
echo "						the highest level of quality in everything we do.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic16.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>			    \n"; 
echo "       		</div>\n"; 
echo "       		<div class=\"container\" style=\"color:#000\">\n"; 
echo "       			 <div class=\"gallery-head text-center\">\n"; 
echo "				  <h3 style=\"color:#FFF\">Our capability</h3>\n"; 
echo "				  <p> </p>\n"; 
echo "				  <span> </span>\n"; 
echo "			    </div>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic17.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>We are experienced and have specialist technical expertise\n"; 
echo "						combined with good business knowledge. Our commitment to very\n"; 
echo "						high professional standards and practices is unwavering. We are\n"; 
echo "						capable of delivering measurable improvements and results in your\n"; 
echo "						business.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Our solutions are workable and effective. We offer that stellar service\n"; 
echo "						that makes a difference.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic18.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>			    \n"; 
echo "       		</div>\n"; 
echo "       	</div>\n"; 
echo "       	<div class=\"first\" id=\"capability\">\n"; 
echo "			<div class=\"container\" style=\"color:#000\">\n"; 
echo "       			 <div class=\"gallery-head text-center\">\n"; 
echo "       			 <h3 style=\"color:#FFF\">Capacity building</h3>\n"; 
echo "				  <h4 style=\"color:#FFF\">We help you find the right talent; put the right talent in the right place and at\n"; 
echo "					the right time. Our capacity building interventions include:</h4>\n"; 
echo "				  <span> </span>\n"; 
echo "			    </div>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic19.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Design of a Learning Management System as well as a Talent\n"; 
echo "						management Framework.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Design of Competency Framework to guide employee training and\n"; 
echo "						development.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic20.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic21.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Development of career planning and progression programs.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Design of Management Development Plans and the delivery of\n"; 
echo "						Management Development programs.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic22.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list1\">\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic23.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>Design of a winning customer service strategy system and\n"; 
echo "						processes.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>\n"; 
echo "			    <ul class=\"list2\">\n"; 
echo "			    	<li class=\"list1_desc\">\n"; 
echo "			    		<h4>HR Project Management support.</h4>\n"; 
echo "			    	</li>\n"; 
echo "			    	<li class=\"list1_img\"><img src=\"images/pic24.jpg\" class=\"img-responsive\" alt=\"\"/></li>\n"; 
echo "			    	<div class=\"clearfix\"> </div>\n"; 
echo "			    </ul>			    \n"; 
echo "       		</div>       		\n"; 
echo "       	</div>\n"; 
echo "       	<!-- <div class=\"contact\">\n"; 
echo "       		<div class=\"container\">\n"; 
echo "       			<div class=\"work_top text-center\">\n"; 
echo "				  <h3>Get Your Facebook Ananlysis Now</h3>\n"; 
echo "				  <p>Enter your details below</p>\n"; 
echo "				  <span> </span>\n"; 
echo "			    </div>\n"; 
echo "			     <div class=\"contact-form_grid\">\n"; 
echo "   					<p>diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam</p>\n"; 
echo "				   <form method=\"post\" action=\"contact-post.html\">\n"; 
echo "					 <input type=\"text\" class=\"textbox\" value=\"Your name\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Your name';}\">\n"; 
echo "					 <input type=\"text\" class=\"textbox\" value=\"Contact Number\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Contact Number';}\">\n"; 
echo "					 <input type=\"text\" class=\"textbox\" value=\"Company Name\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Company Name';}\">\n"; 
echo "					 <input type=\"submit\" value=\"Submit Now\">\n"; 
echo "				   </form>\n"; 
echo "			      </div>\n"; 
echo "   			  </div>\n"; 
echo "       	</div> -->\n"; 
echo "       	<div class=\"work\" id=\"train\">\n"; 
echo "       		<div class=\"container\">\n"; 
echo "       			<div class=\"work_top text-center\">\n"; 
echo "				  <h3>Trainings</h3>\n"; 
echo "				  <p> We provide trainings in various BI and datawarehousing Technologies.<br/> Few of of our featured trainings are:</p>\n"; 
echo "				  <span> </span>\n"; 
echo "			    </div>\n"; 
echo "			\n"; 
echo "			<div class=\"row text-center\">\n"; 
echo "       				<div class=\"col-md-4 about_grid\">\n"; 
echo "                                <img src =\"images/t1.jpg\" alt=\"\" class=\"img-responsive\">\n"; 
echo "                                </div>\n"; 
echo "                                <div class=\"col-md-4 about_grid\">\n"; 
echo "                                 <img src =\"images/t2.jpg\" alt=\"\" class=\"img-responsive\">\n"; 
echo "                                </div>\n"; 
echo "                                <div class=\"col-md-4 about_grid\">\n"; 
echo "                                 <img src =\"images/t3.jpg\" alt=\"\" class=\"img-responsive\">\n"; 
echo "                                </div>\n"; 
echo "                                </div>\n"; 
echo "                                <br/>\n"; 
echo "                               <div class=\"row text-center\">\n"; 
echo "       				<div class=\"col-md-4 about_grid\">\n"; 
echo "                                <img src =\"images/MicroStrategy.png\" alt=\"\" class=\"img-responsive\">\n"; 
echo "                                </div>\n"; 
echo "                                <div class=\"col-md-4 about_grid\">\n"; 
echo "                                 <img src =\"images/t5.jpg\" alt=\"\" class=\"img-responsive\">\n"; 
echo "                                </div>\n"; 
echo "                                <div class=\"col-md-4 about_grid\">\n"; 
echo "                                 <img src =\"images/Informatica.jpg\" alt=\"\" class=\"img-responsive\">\n"; 
echo "                                </div>\n"; 
echo "                                </div>\n"; 
echo "                                <br/><br/><br/><br/>\n"; 
echo "                                \n"; 
echo "                                <h3 style=\"text-align:center;color:#FFF\">\n"; 
echo "                                If you have BI or visualization skills across technologies</h3><br/><br/>\n"; 
echo "                                <h4 style=\"text-align:center;color:#FFF\">\n"; 
echo "                                Send your updated resume with your portfolio<br/><br/>\n"; 
echo " \n"; 
echo "                                info@knacksource.com\n"; 
echo "\n"; 
echo "                                </h4>\n"; 
echo "                                \n"; 
echo "		   </div>\n"; 
echo "       	</div>\n";
echo "       	<div id=\"about\" class=\"about\">\n"; 
echo "			<div class=\"container\">\n"; 
echo "       		   <div class=\"gallery-head text-center\">\n"; 
echo "				  <h3>About Us</h3>\n"; 
echo "				  <p>All the information you need about us</p>\n"; 
echo "				  <span> </span>\n"; 
echo "			    </div>\n"; 
echo "       			<div class=\"row text-center\">\n"; 
echo "       				<div class=\"col-md-4 about_grid\">\n"; 
echo "       					<i class=\"icon1\"> </i>\n"; 
echo "       					<h3>Foundation</h3>\n"; 
echo "       					<h4>Founded in 2016, Knacksource Consulting & Training Services is a full service international\n"; 
echo "						human resources management consulting firm with office in the\n"; 
echo "						Bangalore, Karnataka. This Company offers strategic recruiting,\n"; 
echo "						training, and consulting services mostly in Bangalore and also serves\n"; 
echo "						entire Karnataka. Knacksource Consulting & Training Services helps organizations leverage\n"; 
echo "						the power of their people to achieve peak company performance.</h4>\n"; 
echo "       				</div>\n"; 
echo "       				<div class=\"col-md-4 about_grid\">\n"; 
echo "       					<i class=\"icon2\"> </i>\n"; 
echo "       					<h3>Work</h3>\n"; 
echo "       					<h4>Because strategic human resources is one of the last competitive\n"; 
echo "						advantages that exists for many industries, Ankush HR Services\n"; 
echo "						features a full range of services to help companies. Hire the very best\n"; 
echo "						person for each job Increase employee performance through skillbased\n"; 
echo "						training and development and Maximize organizational\n"; 
echo "						effectiveness through human resources outsourcing.</h4>\n"; 
echo "       				</div>\n"; 
echo "       				<div class=\"col-md-4 about_grid\">\n"; 
echo "       					<i class=\"icon3\"> </i>\n"; 
echo "       					<h3>Approach</h3>\n"; 
echo "       					<h4>Company's unique approach combines two core competencies of\n"; 
echo "						business process: outsourcing and performance management. Our\n"; 
echo "						process is supported by specialists in the behavioral and industrial\n"; 
echo "						sciences and by human resource management experts.</h4>\n"; 
echo "       				</div>\n"; 
echo "       			</div>\n"; 
echo "       			<br>\n"; 
echo "       			<div class=\"row text-center\">\n"; 
echo "       				<div class=\"col-md-4 about_grid\">\n"; 
echo "       					<i class=\"icon1\"> </i>\n"; 
echo "       					<h3>Mission</h3>\n"; 
echo "       					<h4>We ask our clients the right questions, acquire critical information, anticipate emerging needs, and apply our expertise to influence the\n"; 
echo "						best human capital outcomes. We make it possible for remarkable\n"; 
echo "						people to achieve remarkable results.</h4>\n"; 
echo "       				</div>\n"; 
echo "       				<div class=\"col-md-4 about_grid\">\n"; 
echo "       					<i class=\"icon2\"> </i>\n"; 
echo "       					<h3>Vision</h3>\n"; 
echo "       					<h4>To be the leading human resources consulting company in Karnataka\n"; 
echo "						and to be a leading workplace diversity consulting firm.</h4>\n"; 
echo "       				</div>\n"; 
echo "       				<div class=\"col-md-4 about_grid\">\n"; 
echo "       					<i class=\"icon3\"> </i>\n"; 
echo "       					<h3>Values</h3>\n"; 
echo "       					<h4><ul style=\"text-align:left;\">\n"; 
echo "							<li>Professionalism</li>\n"; 
echo "							<li>Perseverance</li>\n"; 
echo "							<li>Belief in the human potential of the Indian continent</li>\n"; 
echo "						</ul></h4>							\n"; 
echo "       				</div>\n"; 
echo "       			</div>\n"; 
echo "       		</div>\n"; 
echo "       	</div>\n"; 
echo "       </div>\n"; 
echo "    <div class=\"footer_top\">\n"; 
echo "      <div class=\"container\" id=\"contactus\">\n"; 
echo "      	<div class=\"col-md-3\">\n"; 
echo "       		<h3>Office Address</h3>\n"; 
echo "       		<p>#8, 2nd Cross, HSR Sector-7, Bangalore, Karnataka- 560068</p><br/><br/><h4 style=\"color:#FFF\">Looking for a job or looking to hire or want to be a BI expert, Get in touch with us. Send email to  info@knacksource.com</h4>\n"; 
echo "      	</div>\n"; 
echo "      	<div class=\"col-md-3\">\n"; 
echo "      		<h3>Links</h3>\n"; 
echo "      		<p >\n"; 
echo "             \n"; 
echo "					<a href=\"#abc\" class=\"scroll\" style=\"color:#FFF\">Your HR</a><br/>\n"; 
echo "					<a href=\"#service\" class=\"scroll\" style=\"color:#FFF\">Services</a><br/>\n"; 
echo "					<a href=\"#whyus\" class=\"scroll\" style=\"color:#FFF\">Why Us</a><br/>\n"; 
echo "					<a href=\"#capability\" class=\"scroll\" style=\"color:#FFF\">Capacity</a><br/>\n"; 
echo "					<a href=\"#train\" class=\"scroll\" style=\"color:#FFF\">Training</a><br/>\n"; 
echo "		<a href=\"#about\" class=\"scroll\" style=\"color:#FFF\">About Us</a>\n"; 
echo "                  \n"; 
echo "		</p>\n"; 
echo "      	</div>\n"; 
echo "      	<div class=\"col-md-6\">       \n"; 
echo "			<h3>Contact US </h3>\n"; 
echo "			<div class=\"footer_form\">\n"; 
echo "   			   <form method=\"post\" >\n"; 
echo "				  <input type=\"text\" class=\"textbox\" name=\"name\" value=\"Name\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Name';}\" ><br/>\n"; 
echo "				  <input type=\"text\" class=\"textbox\" name=\"email\" value=\"Email Address\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Email Address';}\" ><br/>\n"; 
echo "				<input type=\"text\" class=\"textbox\" name=\"mobile\" value=\"Mobile\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Mobile';}\" ><br/>\n";
echo "				  <textarea rows=\"4\" cols=\"50\" value=\"Message\" name=\"message\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Message';}\">\n"; 
echo "				  </textarea>\n"; 
echo "				 <button type=\"submit\" name=\"submit\" onclick=\"myFunction()\">Submit</button>\n"; 
echo "			   </form>\n"; 
echo "			</div>\n"; 
echo "       	</div>\n"; 
echo "      </div>\n"; 
echo "   	</div>    \n"; 
echo "   	<div class=\"footer-bottom\">\n"; 
echo "   		<div class=\"container\">\n"; 
echo "   			<div class=\"copy\">\n"; 
echo "		    	<p>&copy; 2016 Created by <a href=\"http://www.freelancer.in/u/robinhood700011.html\" target=\"_blank\"><span style=\"color:#000\">robinhood700011</span></a></p>\n"; 
echo "			</div>\n"; 
echo "   		</div>\n"; 
echo "   </div>\n"; 
echo "   <script type=\"text/javascript\">\n"; 
echo "						$(document).ready(function() {\n"; 
echo "							/*\n"; 
echo "							var defaults = {\n"; 
echo "					  			containerID: 'toTop', // fading element id\n"; 
echo "								containerHoverID: 'toTopHover', // fading element hover id\n"; 
echo "								scrollSpeed: 1200,\n"; 
echo "								easingType: 'linear' \n"; 
echo "					 		};\n"; 
echo "							*/\n"; 
echo "							\n"; 
echo "							$().UItoTop({ easingType: 'easeOutQuart' });\n"; 
echo "							\n"; 
echo "						});\n"; 
echo "					</script>\n"; 
echo "	<a href=\"#\" id=\"toTop\" style=\"display: block;\"> <span id=\"toTopHover\" ></span></a>\n"; 
echo "</body>\n"; 
echo "</html>\n";
if(isset($_POST['submit']))
 {
	$name = $_POST['name'];
	
	$email = $_POST['email'];
	$query = $_POST['message'];
        $mob = $_POST['mobile'];
	$email_from = $name.'<'.$email.'>';

 $to="info@redbookstall.com";
 $subject="Enquiry!";
 $headers  = 'MIME-Version: 1.0' . "\r\n";
 $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
 $headers .= "From: ".$email_from."\r\n";
 $message="	   
         <br>
 		 Name:
		 $name   
         <br>   
         <br>
 		 Email
		 $email 
                 <br>
                 Phone :
                 $mob
         <br>
		 <br>
 		 Message:
		 $query
      
   ";
	if(mail($to,$subject,$message,$headers))
	{ 	
		

	}
 }
 
?>
